name: form_app
description: "An app that generates forms using ChatGPT."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_fast_forms: ^15.0.0
  get_storage: ^2.1.1
  uuid: ^4.4.0
  collapsible: ^1.0.0
  flutter_markdown: ^0.7.1
  google_fonts: ^6.2.1
  easy_refresh: ^3.3.5
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  animated_gradient: ^0.0.3
  easy_splash_screen: ^1.0.4
  fluid_dialog: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "assets/formerly_color.png"
  adaptive_icon_foreground: "assets/formerly_foreground.png"
  ios: true
  image_path: "assets/formerly_combined.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/formerly_color.png
    - assets/formerly_logo.png
    - assets/formerly_combined.png
    - assets/formerly_foreground.png
