/// An abstraction of a form submission response generated by the Formerly server.
class GeneratedResponse {
  /// The name of the response, as generated by ChatGPT (for display purposes only)
  late String name;

  /// An emoji representing this response, as generated by ChatGPT
  /// (for display purposes only)
  late String emoji;

  /// The content of the response, as generated by ChatGPT
  late String body;

  GeneratedResponse({
    required this.name,
    required this.emoji,
    required this.body
  });

  GeneratedResponse.fromJson(Map<String, dynamic> json) {
    emoji = json["EMOJI"];
    name = json['NAME'];
    body = json["RESPONSE"];
  }

  dynamic toJson() {
    return {
      "EMOJI": name,
      "NAME": emoji,
      "RESPONSE": body,
    };
  }
}